language: rust
cache: cargo
rust:
 - stable
 - beta
 - nightly
env: RUN=BUILD
before_script: rustup target add thumbv7m-none-eabi
script:
 - cargo build --release --examples
matrix:
  include:
    - rust: stable
      env: RUN=FMT
      before_script:
       - rustup component add rustfmt clippy
       - rustup target add thumbv7m-none-eabi
      script:
       - cargo fmt --all -- --check
       - cargo clippy --all
